In [16]:
import torch

x = torch.ones(5)  # input tensor
print(x)
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
print(w)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
print(b)
print(z)
# 多分类并存，ovo
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)  
print(loss)

tensor([1., 1., 1., 1., 1.])
tensor([[ 0.2569, -1.9893, -1.0647],
        [ 0.2588,  0.8038, -0.3456],
        [ 1.3742, -2.2598,  0.0086],
        [-0.3898, -0.1177, -0.8468],
        [ 0.4352, -0.4965, -0.3183]], requires_grad=True)
tensor([-0.2517, -0.6549,  1.1574], requires_grad=True)
tensor([ 1.6837, -4.7144, -1.4095], grad_fn=<AddBackward0>)
tensor(0.6938, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [21]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-np.array(x)))
print(np.mean(np.log(1 - sigmoid([-1.4628, -3.2625,  2.0821]))))

print(-sigmoid([-1.4628, -3.2625,  2.0821]))

-0.8151563670442408
[-0.18803945 -0.03688031 -0.88915118]
-2.999034290271132 -2.99839918699187 -2.9998352901484484


In [12]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964]])
tensor([0.0627, 0.0123, 0.2964])


In [22]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)
# 您可能希望禁用梯度跟踪的原因如下：
# 将神经网络中的某些参数标记为冻结参数。这是微调预训练网络的一个非常常见的场景
# 当您只进行前向传递时加快计算速度，因为在不跟踪梯度的张量上进行计算会更有效。

True
False
