In [16]:
import torch

x = torch.ones(5)  # input tensor
print(x)
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
print(w)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
print(b)
print(z)
# 多分类并存，ovo
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)  
print(loss)

tensor([1., 1., 1., 1., 1.])
tensor([[ 0.2569, -1.9893, -1.0647],
        [ 0.2588,  0.8038, -0.3456],
        [ 1.3742, -2.2598,  0.0086],
        [-0.3898, -0.1177, -0.8468],
        [ 0.4352, -0.4965, -0.3183]], requires_grad=True)
tensor([-0.2517, -0.6549,  1.1574], requires_grad=True)
tensor([ 1.6837, -4.7144, -1.4095], grad_fn=<AddBackward0>)
tensor(0.6938, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [21]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-np.array(x)))
print(np.mean(np.log(1 - sigmoid([-1.4628, -3.2625,  2.0821]))))

print(-sigmoid([-1.4628, -3.2625,  2.0821]))

-0.8151563670442408
[-0.18803945 -0.03688031 -0.88915118]
-2.999034290271132 -2.99839918699187 -2.9998352901484484


In [12]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964],
        [0.0627, 0.0123, 0.2964]])
tensor([0.0627, 0.0123, 0.2964])


In [22]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)
# 您可能希望禁用梯度跟踪的原因如下：
# 将神经网络中的某些参数标记为冻结参数。这是微调预训练网络的一个非常常见的场景
# 当您只进行前向传递时加快计算速度，因为在不跟踪梯度的张量上进行计算会更有效。

True
False


In [63]:
import torch
import torch.nn as nn

import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as pximport numpy as np

model_loss = SumLoss()

x = torch.tensor([2, 3], dtype=torch.float, requires_grad=True)
print(x)
y = torch.tensor([4, 5], dtype=torch.float, requires_grad=True)
z = x * y
print(z)
# loss = model_loss(z, torch.tensor([9, 10]))
loss = torch.mean(torch.pow((sum(z) - torch.tensor([9])), 2))
print(loss)
loss.backward()
print(x.grad)


tensor([2., 3.], requires_grad=True)
tensor([ 8., 15.], grad_fn=<MulBackward0>)
tensor(196., grad_fn=<MeanBackward0>)
tensor([112., 140.])


In [58]:
X = torch.tensor([1.5,3.7], requires_grad=True, dtype=torch.float)
W = torch.tensor(data=[1, 3], requires_grad=True, dtype=torch.float)
Y = W.matmul(X)
print(Y)
loss = torch.mean(torch.pow((Y - torch.tensor([9])), 2))
loss.backward()
print(X.grad)

tensor(12.6000, grad_fn=<DotBackward0>)
tensor([ 7.2000, 21.6000])


In [80]:
def get_x_y():
    # np.random.seed(0)
    # x = np.random.randint(0, 50, 300)
    # y_values = 2 * x + 21
    # x = np.array(x, dtype=np.float32)
    # y = np.array(y_values, dtype=np.float32)
    # x = x.reshape(-1, 1)
    # y = y.reshape(-1, 1)
    torch.manual_seed(0)
    x1 = torch.rand(3, 10)
    x2 = torch.rand(4, 10)
    y = torch.rand(1, 1)
    return x1, x2, y


class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  # 输入的个数，输出的个数

    def forward(self, x):
        out = self.linear(x)
        return out

class SumLoss(nn.Module):
    def __init__(self):
        super(SumLoss, self).__init__()

    def forward(self, x1, x2, y):
        mse_loss = torch.mean(torch.pow((y - (sum(x1) - sum(x2))), 2))
        return mse_loss


x1, x2, y = get_x_y()
model = LinearRegressionModel(10, 1)
epochs = 1000  # 迭代次数
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
model_loss = SumLoss()
for epoch in range(epochs):
    optimizer.zero_grad()
    # 前向传播
    z1 = model(x1)
    z2 = model(x2)
    # 计算损失
    loss = model_loss(z1, z2, y)
    # 返向传播
    loss.backward()
    optimizer.step()
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))



epoch 0, loss 0.19293731451034546
epoch 50, loss 0.03541993349790573
epoch 100, loss 0.006502497475594282
epoch 150, loss 0.0011937402887269855
epoch 200, loss 0.00021915638353675604
epoch 250, loss 4.0231469029095024e-05
epoch 300, loss 7.385264780168654e-06
epoch 350, loss 1.355877316200349e-06
epoch 400, loss 2.4899620143514767e-07
epoch 450, loss 4.570486566990439e-08
epoch 500, loss 8.390090400212102e-09
epoch 550, loss 1.5499077576919262e-09
epoch 600, loss 2.8403079888050797e-10
epoch 650, loss 4.863309754910006e-11
epoch 700, loss 1.2366996315904544e-11
epoch 750, loss 6.956435427696306e-12
epoch 800, loss 4.92961227394062e-12
epoch 850, loss 4.540590126111965e-12
epoch 900, loss 4.106937012693379e-12
epoch 950, loss 3.752553823233029e-12
